use strict;
use warnings;

use inc::Module::Install;

name     'Artemis-CLI';
all_from 'lib/Artemis/CLI.pm';
author   'OSRC SysInt Team <osrc-sysint@elbe.amd.com>';
license  'freebsd';

build_requires 'Test::More';
build_requires 'Test::Perl::Critic';
build_requires 'Test::Fixture::DBIC::Schema';
build_requires 'DBIx::Class'     => '0.08112';
build_requires 'Artemis::Test'   => '2.010005';
build_requires 'SQL::Translator' => '0.11003';

requires 'perl'                      => '5.010';
requires 'parent'                    => 0;
requires 'App::Cmd'                  => '0.301';
requires 'DBIx::Class::TimeStamp'    => 0;
requires 'File::Slurp'               => 0;
requires 'IO::Socket'                => 0;
requires 'Template'                  => 0;
requires 'Artemis::Model'            => '2.010003';
requires 'Artemis::Config'           => '2.010003';
requires 'Artemis::Schema'           => '2.010022';
requires 'Artemis::Cmd'              => '2.010029';
requires 'Data::Dumper'              => 0;
requires 'DateTime::Format::Natural' => 0;
requires 'YAML::Syck'                => 0;
requires 'Moose'                     => 0;
requires 'MooseX::LazyRequire'       => '0.06';
install_script glob('bin/*');
WriteAll;

